#! /usr/bin/python

#
# BOXSTRAP
# by Camron Flanders <camron[dot]flanders[squiggly-at-symbol]gmail[dot]com>
#
# This is a bootstrapping script to help setup a new environment using your dropbox.
#
# Copyright (c) 2009, Camron Flanders
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the developer nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY Camron Flanders ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL Camron Flanders BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

import sys
import os
import re
import logging
import optparse

logging.basicConfig(level	= logging.INFO,
					format	= '[%(name)s | %(levelname)s]: %(message)s',)
log = logging.getLogger('boxStrap')

# PATHS TO ACT ON
#
# relative location paths to our Dropbox root. We will recurse unless told not to by config.
PATHS_TO_PROCESS = ['paths', 'go', 'here',]
#

# DRY RUN
#
# Turn this on if you want to see the paths, but not actually
# link files to their destinations
DRY_RUN = True
#

# DROPBOX LOCATION
#
# We assume that we are being run from the root of your Dropbox
# if not, we will need the path to root of Dropbox.
DROPBOX_LOCATION = os.path.abspath(os.getcwd())
#

# CONFIG FILES
#
# These config files will describe what to exclude, and how we should
# treat the directory. If it's not found we will symlink the directory
# as a whole. if file exists but is empty, we will symlink contents of
# the directory. If the path is a file, we just symlink. 
# more options described in help.
CONFIG_FILE_NAME = "boxStrapConfig"
#

# DEFAULT DESTINATION PATH
#
# We will assume you are symlinking to your $HOME directory, if you
# want to change this - globally - do so here, otherwise override
# on a directory basis in your CONFIG FILES
DEFAULT_DESTINATION = os.path.abspath(os.path.expanduser("~"))
#

# REPLACE EXISTING
#
# If this is true, we will remove existing link/file/directory at
# the destination path and replace with our new one.
#
# PLEASE USE WITH CAUTION, THIS MIGHT REPLACE SOMETHING YOU NEED
REPLACE_EXISTING = False
#

# YOUR CRONTAB
#
# If you have a custom crontab, we will add it to the system crontab
# for the current user. Enable and set your path.
#
INSTALL_CUSTOM_CRONTAB = False
#
CRONTAB_LOCATION = 'path/to/custom/crontab'
CRONTAB_LOCATION = os.path.abspath(os.path.join(DROPBOX_LOCATION, CRONTAB_LOCATION))
#

# PATH REPLACEMENTS CONFIGURATION
#
# I wish there was a nicer way to guarentee the replacement order, but we need to make sure
# '-' comes before 'dash' or else the 'dash' replacement will get replaced by spaces from '-'.
#
# If there is another way -- contact me @ camron[dot]flanders[squiggly-at-symbol]gmail[dot]com
REPLACEMENT_ORDER = ['slash', 'dot', '-', 'dash',]
#
PATH_REPLACEMENTS = {"slash": "/",
                     "dash": "-", 
                     "dot": ".", 
                     "-": "", }
#

class Configuration():
    """ 
    This is our config object, supports our directory-specific overrides.
    
    """
    def __init__(self, path=None):
        # if True, this tells script to link entire directory, not files contained
        self._link_dir = False

        # if link_dir is true, we can specifiy a set of files in that directory that
        # need to be linked elsewhere, outside of the directory.
        self._link_only = []

        # tells script (if not linking dir) which files to not link
        self._excludes = []

        # tells script whether to recurse past root of directory
        self._recurse = True

        # override for link destination
        self._destination = DEFAULT_DESTINATION

        if path and os.path.exists(path):
            self.load_custom_config(path)

    #
    # our properties have custom setters so we can 
    # validate our input appropriately.
    #
    # I think this is a bit messy, but it's also
    # the best (as far as I know) for backwards
    # compatibility on old Python versions.
    #
    def get_link_dir(self):
        return self._link_dir
    def set_link_dir(self, ld):
        self._link_dir = self.resolve_boolean(ld)

    link_dir = property(get_link_dir, set_link_dir)

    def get_link_only(self):
        return self._link_only
    def set_link_only(self, pa):
        self._link_only = self.resolve_path_array(pa)

    link_only = property(get_link_dir, set_link_dir)

    def get_excludes(self):
        return self._excludes
    def set_excludes(self, exclude):
        self._excludes = self.resolve_path_array(exclude)

    excludes = property(get_excludes, set_excludes)

    def get_recurse(self):
        return self._recurse
    def set_recurse(self, r):
        self._recurse = self.resolve_boolean(r)

    recurse = property(get_recurse, set_recurse)

    def get_destination(self):
        return self._destination
    def set_destination(self, d):
        self._destination = os.path.abspath(d.strip())

    destination = property(get_destination, set_destination)
    #
    # end of properties
    #

    #
    # validators
    #
    def resolve_boolean(self, bool):
        """ takes a variety of boolean values and makes it work for us """
        if r.upper() in ['NO', 'FALSE', '0']:
            return False
        else:
            return True

    def resolve_path_array(self, pArray):
        """ this splits up our comma separated paths """
        rtnArray = []
        for i in pArray.split(","):
            rtnArray.append(i.strip())
        return rtnArray
    #
    # end of validator methods
    #

    def load_custom_config(self, path):
        """
        This is how we load up a custom config, a bit hackish since this 
        whole thing was written in an hour...might work on cleaning it up
        a bit down the road.

        """
        re_map = {'excludes':re.compile("excludes=(.*)"), 
                  'recurse':re.compile("recurse=([\w]+)"), 
                  'destination':re.compile("destination=(.*)"), 
                  'link_dir':re.compile("link_dir=([\w]+)"), 
                  'link_only':re.compile("link_only=([\w]+)"), }

        config_file = open(path)
        config_string = config_file.read()

        for line in config_string.split("\n"):
            for k,v in re_map.iteritems():
                match = re.match(v, line, re.M)
                try:
                    setattr(self, k, match.group(1))
                except:
                    pass

# our globals
EXISTING_ARRAY = []

def link_file(src, dest=None, dest_dir=None):
    """
    This will handle swapping my human readable paths for real path
    components and set up a symlink accordingly -- or just print
    what it would've done on a DRY_RUN.
    
    """
    for k in REPLACEMENT_ORDER:
        v = PATH_REPLACEMENTS[k]
        dest = re.sub(k, v, src if not dest else dest)

    dest = os.path.abspath(os.path.join(DEFAULT_DESTINATION if not dest_dir else dest_dir, dest))
    file_name = os.path.basename(dest.rstrip("/"))

    link_text = "Attempting to link from: [%s]\n                                        to: [%s]"
    log.info(link_text % (src, dest))

    if(os.path.exists(dest)):
        if not DRY_RUN and REPLACE_EXISTING:
            try:
                will_replace_string = "We will be removing [%s] before making our link" % dest
                log.warn(will_replace_string)
                os.remove(path)
                log.info("Removed successfully")
            except Exception, e:
                log.error(e)

        if not REPLACE_EXISTING:
            EXISTING_ARRAY.append(src)
            log.info("                     Did not link, file exists.\n")
            return

    if not DRY_RUN:
        os.link(src, dest)
        log.info("Linked successfully\n")

    log.info("\n")

def link_files(file_array):
    """
    Simple function to loop through our file_array, linking happily
    as it goes. If a file has a dest_dir other than our default,
    we take care of that too.
    
    """
    log.info("----------------------")
    log.info("Start linking files...")
    log.info("----------------------")
    for file in file_array:
        if len(file) is 2:
            link_file(file[0], file[1])
        elif len(file) is 3:
            link_file(file[0], file[1], file[2])

    if len(EXISTING_ARRAY) > 0:
        log.warn("These files already existed in destination paths:\n                      %s\n" % "\n                      ".join(EXISTING_ARRAY))
        log.warn("REPLACE_EXISTING is currently set to [%s]." % (REPLACE_EXISTING))
        log.warn("To replace existing files, set REPLACE_EXISTING to True and re-run this script.")
        log.warn("\n")

    log.info("-------------------")
    log.info("Done linking files.")
    log.info("-------------------\n")

def gather_files(cfg=Configuration(), paths=None):
    """
    This processes the paths we give it. When it finds a config file
    we process the files according to the directory-local configuration
    override. This is a recursively called function -- care has been taken
    to make sure we DON'T follow symbolic links, but I cannot guarentee
    in some obscure situations this won't become a loop.
    
    """
    log.debug("paths: %s", paths)

    file_array = []
    for path in paths if paths else PATHS_TO_PROCESS:
        path = os.path.join(DROPBOX_LOCATION, path)

        log.debug("WORKING WITH [%s]", path)
        if(os.path.isdir(path)):
            if not os.path.exists(path):
                log.warn("%s doesn't exist." % path)
                continue

            if not cfg.recurse:
                continue

            cfg = Configuration(os.path.join(path, CONFIG_FILE_NAME))

            if cfg.link_dir:
                file_array.append((path, os.path.join(cfg.destination, os.path.basename(path.rstrip("/"))), cfg.destination),)
                paths = []

                if isinstance(cfg.link_only, (list, tuple,)):
                    for p in cfg.link_only:
                        paths.append(os.path.join(path, p))
                elif isinstance(cfg.link_only, (unicode, str)):
                    paths.append(os.path.join(path,cfg.link_only))
                    
                if len(paths) > 0:
                    file_array.extend(gather_files(cfg=cfg, paths=paths))
            else:
                paths = []
                log.debug("Processing sub-files...")
                for item in os.listdir(path):
                    if item in cfg.excludes:
                        log.debug("[%s] excluded by [%s]" % (item, cfg.excludes))
                        continue
                    elif re.match("\.", item):
                        log.debug("[%s] dotfile" % item)
                        continue
                    elif item == CONFIG_FILE_NAME:
                        log.debug("[%s] our config, auto-excluding" % item)
                        continue
                    else:
                        log.debug("[%s] adding to array" % item)
                        paths.append(os.path.join(path, item)) 

                file_array.extend(gather_files(cfg=cfg, paths=paths))
        else:
            if not os.path.exists(path):
                log.warn("%s doesn't exist." % path)
                continue

            file_array.append((path, os.path.join(cfg.destination, os.path.basename(path.rstrip("/"))), cfg.destination),)

    log.debug("file_array: %s" % file_array)
    return file_array

def add_crontab(replace=REPLACE_EXISTING):
    """
    Simple function to add a set of custom crontab entries to 
    the current user's crontab.
    
    """
    log.info("----------------------")
    log.info("%s your crontab..." % ("Replacing" if replace else "Installing"))
    log.info("----------------------\n")
    try:
        if INSTALL_CUSTOM_CRONTAB:
            ct = open(CRONTAB_LOCATION)
            log.info("your crontab:\n\n%s\n" % (ct.read()))
            log.info("---")

            if not DRY_RUN:
                if replace:
                    log.info("Removing existing crontab.")
                    os.system("crontab -r")
                    log.info("Installing new crontab.\n")

                os.system("crontab %s" % CRONTAB_LOCATION)
        else:
            log.info("INSTALL_CUSTOM_CRONTAB is set to False.")
            log.info("For us to install your crontab, you must switch INSTALL_CUSTOM_CRONTAB to True and set CRONTAB_LOCATION to the correct path.\n")
    except Exception, e:
        log.warn("Looks like your CRONTAB_LOCATION path isn't properly configured.")
        log.warn("Specific Error: %s", e)

    log.info("----------------------")
    log.info("Done with crontab")
    log.info("----------------------")

def install_only_crontab(option, opt_str, value, parser, *args):
    """
    If command line is run with -c or --install-crontab then we will
    install just the custom crontab, then exit.
    
    """
    if args and args[0] == 'True': replace = True
    else: replace = False
    add_crontab(replace)
    sys.exit(0)

def generate_config_file(option, opt_str, value, parser):
    path = os.path.abspath(value)
    cfg_file = os.path.join(path, CONFIG_FILE_NAME)

    if os.path.exists(cfg_file):
        log.warn("[%s] already exists, NOT creating a new one." % cfg_file)
    else:
        log.warn("Generating config file for [%s]" % path)

        default_cfg = Configuration()
        lines = ["# '%s' boxstrap configuration file\n" % os.path.basename(path.rstrip("/"))]

        for k,v in default_cfg.__dict__.iteritems():
            lines.append("%s=%s\n" % (k.lstrip("_"),v))

        file = open(cfg_file, "w")
        file.writelines(lines)
        file.close()

        log.info("config generated.")
    sys.exit(0)

def dry_run_wrapper(function, *args, **kwargs):
    """ 
    A convenience method to wrap the function call in DRY_RUN information.
    
    """
    dry_run_start()

    if isinstance(function, optparse.Option):
        function = args[3]
        function_arg = args[4]

        args = list(args)
        del args[3]

        args = tuple(args)

    function(*args, **kwargs)

    dry_run_end()

def dry_run_start():
    """ 
    A convenience method to output our DRY_RUN info before run. We make sure this the output
    only displays on DRY_RUN.
    
    """
    if DRY_RUN:
        log.error("-----------------------------------------------------------------")
        log.error("THIS IS A DRY RUN, NO FILES WILL BE LINKED, REMOVED, or MODIFIED.")
        log.error("-----------------------------------------------------------------\n")

def dry_run_end():
    """ 
    A convenience method to output our DRY_RUN info after run. We make sure this the output
    only displays on DRY_RUN.
    
    """
    if DRY_RUN:
        log.error("\n")
        log.error("------------------------------------------------------------------------------")
        log.error("REMINDER: THIS WAS A DRY RUN, NO FILES HAVE BEEN LINKED, REMOVED, or MODIFIED.")
        log.error("If the output looks correct, set DRY_RUN to True and re-run.")
        log.error("------------------------------------------------------------------------------")

if __name__ == "__main__":
    parser = optparse.OptionParser()
    parser.add_option("-q", "--quiet",   dest="level", action="store_const", const=logging.WARN, help="Only show errors.")
    parser.add_option("-v", "--verbose", dest="level", action="store_const", const=logging.DEBUG, help="Show all information, useful for debugging.")
    parser.add_option("-c", "--install-crontab", action="callback", callback=dry_run_wrapper, callback_args=(install_only_crontab,), help="This will install just your custom crontab.")
    parser.add_option("-r", "--replace-crontab", action="callback", callback_args=(install_only_crontab, 'True',), callback=dry_run_wrapper, help="This will remove the current crontab and install your custom one.")
    parser.add_option("-g", "--generate-config", action="callback", metavar="DIR", nargs=1, type='string', callback=generate_config_file, help="This generates a config file filled with the defaults in DIR")

    opts, args = parser.parse_args(sys.argv)
    log.setLevel(opts.level)

    if PATHS_TO_PROCESS == ['paths', 'go', 'here',]:
        log.error("----------------------------------------------------------------")
        log.error("You need to set PATHS_TO_PROCESS before we can execute. Exiting.")
        log.error("----------------------------------------------------------------")
        sys.exit(0)

    dry_run_start()

    file_array = gather_files()
    link_files(file_array)
    add_crontab()

    dry_run_end()
